2021-12-23 15:05:04,355 - WARNING - Invalid phone: Row 4, Row ID 3,14152549431

2021-12-23 15:05:04,356 - WARNING - Invalid phone: Row 5, Row ID 4,1.65E+15

2021-12-23 15:05:05,345 - ERROR - Row 7
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:05,399 - ERROR - Row 9
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:05,400 - WARNING - Invalid phone: Row 13, Row ID 400,124567

2021-12-23 15:05:05,412 - ERROR - Row 3
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:05,458 - ERROR - Row 11
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:05,851 - ERROR - Row 13 - Status Code:400 - The query does not contain any valid name/username/user_id/phone/email/address to search by
2021-12-23 15:05:05,851 - WARNING - Row 13 - API Warning: We could not parse a valid username or user_id from the provided url 'google.com'
2021-12-23 15:05:05,851 - WARNING - Row 13 could not get API response
2021-12-23 15:05:06,179 - ERROR - Row 5
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:06,240 - ERROR - Row 6
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:06,283 - ERROR - Row 4
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:06,358 - ERROR - Row 10
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:06,596 - ERROR - Row 8
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
2021-12-23 15:05:06,650 - ERROR - Row 2
Traceback (most recent call last):
  File "C:\Users\Matthew Curtis\Documents\Github-Pipl\Tests\Full Featured Example\Python CSV script Example - Full featured.py", line 234, in do_work
    if api_response.Person.Available_data.emails:
AttributeError: 'SearchAPIResponse' object has no attribute 'Person'
